# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e45a9a1c2684ebcf4d13cfd7dd954db9cfdead3d6cd9cc028a98a8e1e1d2b03bf230b4ef8da439d0f5178fcad249a6151ffffed57daffe4903308fa6b4a2fbf

test:
  secret_key_base: e074978d63fe652525c9081ff059834a8fe401d891dcc60eba69b1d1f8f120b05a41890ba469feb0399c16690d0bd11a8ce28933c93e53988ca43b26e6219bf7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
